<?php 
include "akses.php";
include "../admin/header.php";
?>
<link rel="stylesheet" href="../asset/css/home.css">
<body style="background-image: url('../config/bg-u.jpg');">
	<div id="body">
		<div class="container">
			<header>
				<h3>VISI & MISI</h3>
				<h4>STIE PASAMAN</h4>
			</header>
			<legend>
				<h4>VISI</h4>
				<h5>STIE PASAMAN MENJADIKAN KAMPUS PUSAT LAHIRNYA INTELEKTUAL EKONOMI DENGAN KUALITAS TERBAIK YANG MAMPU BERKOMPETISI DI TINGKAT DAERAH DAN NASIONAL</h5>
			</legend>
			<legend>
				<h4>MISI</h4>
				<h5>1. MENYELENGGARAKAN PENDIDIKAN AKADEMIK DIBIDANG ILMU EKONOMI BERBASIS KOMPETENSI.</h5>
				<h5>2. MEMBERDAYAKAN PROGRAM STUDI ILMU EKONOMI UNTUK LEBIH BERKREATIFITAS DAN LEBIH PROFESIONAL DALAM MENCAPAI STANDAR KOMPETENSI.</h5>
				<h5>3. MENINGKATKAN DAYA AKUNTABILITAS, KREATIFITAS CIVITAS AKADEMIKA DALAM MENGGALI, MENGEMBANGKAN DAN MENERAPKAN ILMU EKONOMI SESUAI DENGAN PARADIGMA BARU.</h5>
				<h5>4. MEMBERDAYAKAN CIVITAS AKADEMIKA DAN SEMUA UNSUR YANG TERKAIT UNTUK MAMPU BERINOVASI, BERDISIPLIN, BERTINDAK KREATIF DAN PROAKTIF BERFIKIR KRITIS DAN ANALITIS SERTA MAMPU BERADAPTASI DENGAN PERUBAHAN.</h5>
				<h5>5. MEMBERDAYAKAN CIVITAS AKADEMIKA DAN SEMUA UNSUR YANG TERKAIT UNTUK MAMPU BEKERJASAMA, MEMBUKA JARINGAN BAIK DITINGKAT DAERAH, NASIONAL, MAUPUN INTERNASIONAL.</h5>
				<h5>6. MENINGKATKAN KETERAMPILAN KOMUNIKASI MASYARAKAT KAMPUS DALAM MEMBINA HUBUNGAN KOMUNIKASI DENGAN PUBLIK DAN INTERNASIONAL.</h5>
				<h5>7. MEMBANGUN KONSEP DIRI DALAM MEMBENTUK CITRA KAMPUS YANG BERKUALITAS DAN INTELEK SERTA MORAL DAN BERAKHLAK MULIA.</h5>
			</legend>
		</div>
	</div>
</body>
<?php 
include "../admin/footer.php";
?>